### PR TITLE
Added slide animation of recyclerView with MotionLayout

### PR DESCRIPTION
**Pull request by GeorgCantor**
**- Summary**

Impoving UI 

**- Description for the changelog**

Added slide animation of recyclerView with MotionLayout

**- A picture or screenshot regarding change (not mandatory but encouraged)**

[](https://postimg.cc/mP8T7dCD)

### CODE REVIEW

**Comment by PatilShreyas** [comment]
@GeorgCantor This change is good but earlier when internet is on/off, status was displayed and animated. This is not working after this. Can you look into it?

**Comment by GeorgCantor** [comment]
> @GeorgCantor This change is good but earlier when internet is on/off, status was displayed and animated. This is not working after this. Can you look into it?

I checked. Above, a status bar is displayed with the inscription No Internet

**Comment by GeorgCantor** [comment]
> @GeorgCantor This change is good but earlier when internet is on/off, status was displayed and animated. This is not working after this. Can you look into it?

I ran your version and found no difference. Everything works the same.

**Comment by GeorgCantor** [comment]
> @GeorgCantor This change is good but earlier when internet is on/off, status was displayed and animated. This is not working after this. Can you look into it?

Yes, I saw that the status is overlapping. I will try to fix it

**Comment by GeorgCantor** [comment]
> @GeorgCantor This change is good but earlier when internet is on/off, status was displayed and animated. This is not working after this. Can you look into it?

Now I have checked and everything works as it should. Status visible.

**Comment by PatilShreyas** [comment]
@GeorgCantor See this video: I want it like this: https://twitter.com/i/status/1241624332758966273.

Currently (in your implementation), if the internet is back then that status is not hiding.

**Comment by GeorgCantor** [comment]
> @GeorgCantor
> 
> ### Expected behaviour
> Here, the expected behaviour is that status should show/hide whenever connectivity state changes.
> See this video: I want it like this: https://twitter.com/i/status/1241624332758966273.
> 
> ### Your implementation
> Currently (in your implementation), if the internet is back then that status is not hiding.
> 
> ezgif com-gif-maker
> 
> I hope you get that point.

Ok. I will try to fix it

**Comment by GeorgCantor** [comment]
[](https://postimg.cc/D8QjCvvG)

**Comment by PatilShreyas** [comment]
It's looking nice now. But if you take a look at the latest version of Foodium app then you can see that transition is smoother. That status comes and goes with smooth effect as you can see in below video. Can you implement like that?: 

ezgif com-gif-maker (1)

---

Try this app from the following link for trying it: 👇🏻 
[Foodium App](https://github.com/PatilShreyas/Foodium/releases/latest/download/app.apk)

**Comment by GeorgCantor** [comment]
Ok I will try to do it

**Comment by PatilShreyas** [comment]
@GeorgCantor Any update on this?

**Pull request closed without merging**
